#!/bin/sh
#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#

# Remove aclocal.m4 as it'll break some builds...
rm -rf aclocal.m4 autom4te*.cache

echo "Creating configure ..."
libtoolize --force
automake --force-missing --add-missing
### do some work to toss config.cache?
${AUTOCONF:-autoconf}
if [ $? -gt 0 ]; then
  echo "autoconf failed"
  exit 1
fi

# Remove autoconf cache again
rm -rf autom4te*.cache

# Create RPM Spec file
echo rebuilding rpm spec file
REVISION=`build/get-version.sh all include/tcn_version.h TCN`
# Strip everything behind "-"
VERSION=`echo $REVISION | sed -e 's/-.*//'`
# Strip everything before "-"
RELEASE=`echo $REVISION | sed -e 's/.*-//'`
# Handle case of no "-" in REVISION
if [ "x$RELEASE" = "x$REVISION" ]; then
  RELEASE=1
fi
echo "Using version '$VERSION' and release '$RELEASE' in RPM spec file"
sed -e "s/TCN_VERSION/$VERSION/" \
    -e "s/TCN_RELEASE/$RELEASE/" \
    ./build/rpm/tcnative.spec.in \
    > tcnative.spec
